workflows:
  react-native-apk:
    name: React Native APK Build
    max_build_duration: 90
    environment:
      node: 16
      java: 17
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Expo prebuild (clean)
        script: |
          npx expo prebuild --clean
      - name: Build Android Release
        script: |
          cd android
          ./gradlew clean assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
